import type { Category, Product } from './types';

export const catalogCategories: Category[] = [
  { id: 'keyboards', name: 'Keyboards' },
  { id: 'mouse', name: 'Mouse' },
  { id: 'headsets', name: 'Headsets' },
  { id: 'monitors', name: 'Monitors' },
  { id: 'storage', name: 'Storage' },
];

export const catalogProducts: Product[] = [
  {
    id: 1,
    slug: 'keychron-q6-max',
    name: 'Keychron Q6 Max',
    brand: 'Keychron',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    priceTHB: 8990,
    image: 'https://images.unsplash.com/photo-1725755751265-6a7b23077316',
    imageAlt: 'Keychron Q6 Max mechanical keyboard',
    stockQuantity: 8,
    badge: 'New',
  },
  {
    id: 2,
    slug: 'keychron-k8-pro',
    name: 'Keychron K8 Pro',
    brand: 'Keychron',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    priceTHB: 5490,
    image: 'https://images.unsplash.com/photo-1641611895204-ed582ce8b53f',
    imageAlt: 'Keychron K8 Pro mechanical keyboard',
    stockQuantity: 14,
  },
  {
    id: 3,
    slug: 'logitech-g-pro-x-superlight-2',
    name: 'Logitech G Pro X Superlight 2',
    brand: 'Logitech',
    categoryId: 'mouse',
    categoryName: 'Mouse',
    priceTHB: 4990,
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1028cb4b2-1772845470794.png',
    imageAlt: 'Logitech G Pro X Superlight 2 mouse',
    stockQuantity: 11,
    badge: 'Sale',
  },
  {
    id: 4,
    slug: 'hyperx-cloud-iii',
    name: 'HyperX Cloud III',
    brand: 'HyperX',
    categoryId: 'headsets',
    categoryName: 'Headsets',
    priceTHB: 3290,
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1d5ff1a26-1770408083454.png',
    imageAlt: 'HyperX Cloud III gaming headset',
    stockQuantity: 6,
  },
  {
    id: 5,
    slug: 'samsung-odyssey-g5-27',
    name: 'Samsung Odyssey G5 27',
    brand: 'Samsung',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    priceTHB: 8990,
    image: 'https://images.unsplash.com/photo-1603481546164-959efb269a4e',
    imageAlt: 'Samsung Odyssey G5 27-inch monitor',
    stockQuantity: 0,
  },
  {
    id: 6,
    slug: 'samsung-990-evo-plus-1tb',
    name: 'Samsung 990 EVO Plus 1TB',
    brand: 'Samsung',
    categoryId: 'storage',
    categoryName: 'Storage',
    priceTHB: 3790,
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_158627142-1770937534812.png',
    imageAlt: 'Samsung 990 EVO Plus 1TB SSD',
    stockQuantity: 9,
    badge: 'Limited',
  },
];
