import type { Category, Product } from './types';

export const catalogCategories: Category[] = [
  { id: 'keyboards', name: 'Keyboards' },
  { id: 'mice', name: 'Mice' },
  { id: 'headsets', name: 'Headsets' },
  { id: 'monitors', name: 'Monitors' },
  { id: 'storage', name: 'Storage' },
];

export const catalogProducts: Product[] = [
  {
    id: 1,
    slug: 'keychron-q6-max',
    name: 'Keychron Q6 Max',
    brand: 'Keychron',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    priceTHB: 8990,
    image: '/images/products/keychron-q6-max.jpg',
    imageAlt: 'Keychron Q6 Max mechanical keyboard',
    stockQuantity: 8,
    badge: 'New',
  },
  {
    id: 2,
    slug: 'keychron-k8-pro',
    name: 'Keychron K8 Pro',
    brand: 'Keychron',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    priceTHB: 5490,
    image: '/images/products/keychron-k8-pro.jpg',
    imageAlt: 'Keychron K8 Pro mechanical keyboard',
    stockQuantity: 14,
  },
  {
    id: 3,
    slug: 'logitech-g-pro-x-superlight-2',
    name: 'Logitech G Pro X Superlight 2',
    brand: 'Logitech',
    categoryId: 'mice',
    categoryName: 'Mice',
    priceTHB: 4990,
    image: '/images/products/logitech-g-pro-x-superlight-2.jpg',
    imageAlt: 'Logitech G Pro X Superlight 2 mouse',
    stockQuantity: 11,
    badge: 'Sale',
  },
  {
    id: 4,
    slug: 'hyperx-cloud-iii',
    name: 'HyperX Cloud III',
    brand: 'HyperX',
    categoryId: 'headsets',
    categoryName: 'Headsets',
    priceTHB: 3290,
    image: '/images/products/hyperx-cloud-iii.jpg',
    imageAlt: 'HyperX Cloud III gaming headset',
    stockQuantity: 6,
  },
  {
    id: 5,
    slug: 'samsung-odyssey-g5-27',
    name: 'Samsung Odyssey G5 27',
    brand: 'Samsung',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    priceTHB: 8990,
    image: '/images/products/samsung-odyssey-g5-27.jpg',
    imageAlt: 'Samsung Odyssey G5 27-inch monitor',
    stockQuantity: 0,
  },
  {
    id: 6,
    slug: 'samsung-990-evo-plus-1tb',
    name: 'Samsung 990 EVO Plus 1TB',
    brand: 'Samsung',
    categoryId: 'storage',
    categoryName: 'Storage',
    priceTHB: 3790,
    image: '/images/products/samsung-990-evo-plus-1tb.jpg',
    imageAlt: 'Samsung 990 EVO Plus 1TB SSD',
    stockQuantity: 9,
    badge: 'Limited',
  },
];
